// destinations.js

const destinationData = [
    {
      id: 1,
      name: 'Seychelles Island',
      location: 'Indian Ocean',
      img: '', // Unsplash API will populate this
      rating: 4.7,
      category: 'Beach',
    },
    {
      id: 2,
      name: 'Maui Beach',
      location: 'Hawaii, USA',
      img: '',
      rating: 4.9,
      category: 'Beach',
    },
    {
      id: 3,
      name: 'Bora Bora',
      location: 'French Polynesia',
      img: '',
      rating: 4.8,
      category: 'Beach',
    },
    {
      id: 4,
      name: 'Maldives',
      location: 'Indian Ocean',
      img: '',
      rating: 4.6,
      category: 'Beach',
    },
    {
      id: 5,
      name: 'Bondi Beach',
      location: 'Sydney, Australia',
      img: '',
      rating: 4.4,
      category: 'Beach',
    },
    {
      id: 6,
      name: 'Waikiki Beach',
      location: 'Hawaii, USA',
      img: '',
      rating: 4.5,
      category: 'Beach',
    },
    {
      id: 7,
      name: 'Grand Canyon',
      location: 'Arizona, USA',
      img: '',
      rating: 4.9,
      category: 'Mountain',
    },
    {
      id: 8,
      name: 'Mount Everest',
      location: 'Nepal/China',
      img: '',
      rating: 5.0,
      category: 'Mountain',
    },
    {
      id: 9,
      name: 'Rocky Mountains',
      location: 'Colorado, USA',
      img: '',
      rating: 4.7,
      category: 'Mountain',
    },
    {
      id: 10,
      name: 'Mount Kilimanjaro',
      location: 'Tanzania',
      img: '',
      rating: 4.8,
      category: 'Mountain',
    },
    {
      id: 11,
      name: 'Matterhorn',
      location: 'Switzerland',
      img: '',
      rating: 4.9,
      category: 'Mountain',
    },
    {
      id: 12,
      name: 'Mount Fuji',
      location: 'Japan',
      img: '',
      rating: 4.8,
      category: 'Mountain',
    },
    {
      id: 13,
      name: 'Yellowstone National Park',
      location: 'Wyoming, USA',
      img: '',
      rating: 4.8,
      category: 'Park',
    },
    {
      id: 14,
      name: 'Yosemite National Park',
      location: 'California, USA',
      img: '',
      rating: 4.9,
      category: 'Park',
    },
    {
      id: 15,
      name: 'Banff National Park',
      location: 'Canada',
      img: '',
      rating: 4.7,
      category: 'Park',
    },
    {
      id: 16,
      name: 'Kruger National Park',
      location: 'South Africa',
      img: '',
      rating: 4.8,
      category: 'Park',
    },
    {
      id: 17,
      name: 'Serengeti National Park',
      location: 'Tanzania',
      img: '',
      rating: 4.9,
      category: 'Park',
    },
    {
      id: 18,
      name: 'Zion National Park',
      location: 'Utah, USA',
      img: '',
      rating: 4.8,
      category: 'Park',
    },
    {
      id: 19,
      name: 'Plitvice Lakes',
      location: 'Croatia',
      img: '',
      rating: 4.9,
      category: 'Nature',
    },
    {
      id: 20,
      name: 'Galápagos Islands',
      location: 'Ecuador',
      img: '',
      rating: 5.0,
      category: 'Nature',
    },
    {
      id: 21,
      name: 'Amazon Rainforest',
      location: 'South America',
      img: '',
      rating: 4.8,
      category: 'Nature',
    },
    {
      id: 22,
      name: 'Great Barrier Reef',
      location: 'Australia',
      img: '',
      rating: 4.9,
      category: 'Nature',
    },
    {
      id: 23,
      name: 'Iguazu Falls',
      location: 'Argentina/Brazil',
      img: '',
      rating: 4.9,
      category: 'Nature',
    },
    {
      id: 24,
      name: 'Victoria Falls',
      location: 'Zambia/Zimbabwe',
      img: '',
      rating: 4.8,
      category: 'Nature',
    }
  ];
  
  export default destinationData;
  